apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: data-usage-api
build:
  artifacts:
    - image: harbor.cyverse.org/de/data-usage-api
      platforms:
        - "linux/amd64"
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/data-usage-api.yml
